#!/bin/sh
# Robert Bennett
# Version 1.0

# This script takes converts docsys output (or any output for that matter)
# into html format. It takes two parameters. The first parm is a header for
# the web page the second is the file it is converting.

export DATE=`(date --rfc-3339 date)`

echo '<HTML>'
echo '<body>'
echo '<h1 align="center">System Documentation for ' $1 '</h1>'
echo '<h1 align="center">' $DATE '</h1>'
echo ''
echo '<h2>Contents</h2>'
echo ''
echo '<menu>'
echo '  <li><a HREF="#System_info">System info:</a></li>'
echo '  <li><a HREF="#Support_info">Support info:</a></li>'
echo '  <li><a HREF="#Load_Avg">Load Avg:</li>'
echo '  <li><a HREF="#Umask">umask:</li>'
echo '  <li><a HREF="#Hostname">Hostname:</li>'
echo '  <li><a HREF="#Model">Model</a></li>'
#echo '  <li><a HREF="#Target_ID">Targetid</a></li>'
echo '  <li><a HREF="#Hosts_it">Hosts it</a></li>'
echo '  <li><a HREF="#Swapinfo">Swapinfo</a></li>'
echo '  <li><a HREF="#Real_Memory_Size">Real Memory Size</a></li>'
echo '  <li><a HREF="#Memory_slab_info">Memory Slab Info</a></li>'
echo '  <li><a HREF="#Kernel_Parms">Kernel Parms</a></li>'
echo '  <li><a HREF="#System_Startup_Shutdown">System Startup/Shutdown</a></li>'
echo '  <li><a HREF="#chkconfig">chkconfig</a></li>'
echo '  <li><a HREF="#Cron_stuff">Cron stuff</a></li>'
echo '  <li><a HREF="#Ager_Info">Ager Info</a></li>'
#echo '  <li><a HREF="#Checking_for_HA_software">Checking for HA software</a></li>'
echo '  <li><a HREF="#Lan_Info">Lan info:</a></li>'
echo '  <li><a HREF="#Netstat_-i">Netstat -i</a></li>'
echo '  <li><a HREF="#Netstat_-r">Netstat -r:</a></li>'
echo '  <li><a HREF="#ifcfg">ifcfg:</a></li>'
echo '  <li><a HREF="#bonding.conf">bonding.conf:</a></li>'
echo '  <li><a HREF="#sysctl.conf">sysctl.conf:</a></li>'
#echo '  <li><a HREF="#X25_Info">X25 Info:</a></li>'
#echo '  <li><a HREF="#OTS_Software">OTS Software:</a></li>'
echo '  <li><a HREF="#nsswitch.conf">nsswitch.conf:</a></li>'
echo '  <li><a HREF="#DNS_Client_Information_/etc/resolv.conf">DNS Client Information /etc/resolv.conf:</a></li>'
echo '  <li><a HREF="#DNS_Server">DNS Server:</a></li>'
#echo '  <li><a HREF="#Inetd.sec">Inetd.sec:</a></li>'
echo '  <li><a HREF="#/etc/xinetd.conf">/etc/xinetd.conf:</a></li>'
echo '  <li><a HREF="#/etc/services">/etc/services:</a></li>'
echo '  <li><a HREF="#Looking_for_dhcpd">Looking for dhcpd:</a></li>'
echo '  <li><a HREF="#xntpd_config">xntpd config:</a></li>'
echo '  <li><a HREF="#/etc/passwd">/etc/passwd:</a></li>'
echo '  <li><a HREF="#/etc/group">/etc/group:</a></li>'
echo '  <li><a HREF="#Basic_NIS_info">Basic NIS info:</a></li>'
echo '  <li><a HREF="#Any_NFS_exports_or_automounter_stuff">Any NFS exports or automounter stuff:</a></li>'
echo '  <li><a HREF="#/etc/sysconfig/nfs">/etc/sysconfig/nfs:</a></li>'
#echo '  <li><a HREF="#Using_UUCP">Using UUCP:</a></li>'
echo '  <li><a HREF="#Sendmail_Config">Sendmail Config:</a></li>'
echo '  <li><a HREF="#/etc/shells">/etc/shells:</a></li>'
echo '  <li><a HREF="#The_system_Disk_Drives">The system Disk Drives:</a></li>'
echo '  <li><a HREF="#DF_Output">DF Output:</a></li>'
echo '  <li><a HREF="#fstab_information">The fstab information:</a></li>'
echo '  <li><a HREF="#The_fdisk_information">The fdisk information:</a></li>'
echo '  <li><a HREF="#xfs_information">The XFS Information:</a></li>'
echo '  <li><a HREF="#grub.conf_information">The grub.conf information:</a></li>'
echo '  <li><a HREF="#LVM_Info">LVM Info:</a></li>'
echo '  <li><a HREF="#pvs">pvs:</a></li>'
echo '  <li><a HREF="#vgs">vgs:</a></li>'
echo '  <li><a HREF="#lvs">lvs:</a></li>'
echo '  <li><a HREF="#vgdisplay">vgdisplay:</a></li>'
echo '  <li><a HREF="#cpu_information">CPU Information:</a></li>'
echo '  <li><a HREF="#The_entire_IO_subsystem">The entire IO subsystem:</a></li>'
echo '  <li><a HREF="#Installed_Software">Installed Software:</a></li>'
echo '</menu>'
echo '<p>'
while read I
do 
  echo "$I" '<br>'
done <  $2
echo '</body>'
echo '</HTML>'

